---
- name: Create telegraf data directory
  file: 
    path: "{{ VAR_TELEGRAF_DIR }}"
    recurse: yes
    state: directory

- name: Copy telegraf.conf
  copy:
    src: telegraf.conf
    dest: "{{ VAR_TELEGRAF_DIR }}/telegraf.conf"
    mode: 0644

- name: Start telegraf container
  docker_container:
    name: telegraf
    image: telegraf:latest
    pull: yes
    state: started
    env:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
    - "{{ VAR_TELEGRAF_DIR }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /etc:/rootfs/etc:ro
    links:
    - influxdb
    restart_policy: unless-stopped

