---
- name: Create telegraf data directory
  file: 
    path: "{{ VAR_TELEGRAF_DIR }}"
    recurse: yes
    state: directory

- name: Copy telegraf.conf
  copy:
    src: telegraf.conf
    dest: "{{ VAR_TELEGRAF_DIR }}/telegraf.conf"
    mode: 0644

- name: Start telegraf container
  docker_container:
    name: telegraf
    image: telegraf:latest
    pull: yes
    state: started
    volumes:
    - "{{ VAR_TELEGRAF_DIR }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    links:
    - influxdb
    restart_policy: unless-stopped

